---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: service-index-viewer
subjects:
- kind: ServiceAccount
  name: service-index
  namespace: tools
roleRef:
  kind: ClusterRole
  name: virtualservice-reader
  apiGroup: rbac.authorization.k8s.io
